name: restaurant_pos
description: A simple Restaurant POS Flutter app (orders, KOT, billing, taxes/discounts, summaries, WhatsApp link).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  # Printing/Bluetooth stubs: choose one based on your printer model and add native permissions.
  # For many cheap 58/80mm printers, people use blue_thermal_printer or esc_pos_bluetooth + esc_pos_utils.
  # Included code uses url_launcher to show how you'd trigger printing or share; swap in your preferred plugin.
  blue_thermal_printer: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
